---
dependencies:
  - role: jnv.unattended-upgrades
    unattended_mail: 'upgrades@bip.filippo.io'
    unattended_mail_only_on_error: true
    unattended_remove_unused_dependencies: true
    unattended_automatic_reboot: true
    unattended_origins_patterns:
      - 'origin=Debian,codename=${distro_codename},label=Debian-Security'
      - 'origin=TorProject'
