---

- name: /etc/sudoers.d/010_nopasswd
  copy:
    dest: "/etc/sudoers.d/010_nopasswd"
    content: "filippo ALL=(ALL) NOPASSWD: ALL\n"
    mode: 0600
- name: revert /etc/sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^filippo'
    state: absent

- authorized_key:
    user: filippo
    key: "{{ ssh_key }}"
  when: ansible_os_family != "Alpine"
- name: disable users
  user:
    name: "{{ item }}"
    password: "!"
  with_items: "{{ disabled_users | default([]) }}"

- name: /etc/ssh/sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s*{{ item }}'
    line: "{{ item }} no"
  with_items:
    - PermitRootLogin
    - ChallengeResponseAuthentication
    - PasswordAuthentication
  notify:
    - restart ssh

- hostname:
    name: "{{ inventory_hostname_short }}"
- name: remove old hostname from /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.1.1\s'
    state: absent
- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1\s'
    line: "127.0.0.1\t{{ inventory_hostname }} {{ inventory_hostname_short }} localhost.localdomain localhost"
