---
- name: he-ipv6.service
  template:
    src: he-ipv6.service.j2
    dest: /etc/systemd/system/he-ipv6.service
    mode: 0644
- systemd:
    daemon_reload: yes
    name: he-ipv6.service
    state: started
    enabled: yes
