---
- hosts: serial.home.arpa
  remote_user: pi
  become: yes
  tasks:
  - user: name=filippo groups=dialout shell=/bin/bash
  - copy:
      dest: "/etc/sudoers.d/010_nopasswd"
      content: "filippo ALL=(ALL) NOPASSWD: ALL"
      mode: 0600
  - authorized_key: user="{{ item }}" key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWRM9S+MWm5WPOhvVWTUfCURPjdQ2B3NUJtEeDMTLS+9LNpHOvSroHBT0UdjgHBRKFqctWj0cKz2dJ+I93mGYQOvePuSwnTXdwj04xTrX2nW7Spi7MdWAkFHyreoCyUYW4sg6zGCYyBUUYrRqxKpRl6PPArDzjKh9BgzvAcXPwk0GjpTGkt94RemifrBbrvwp7DC4CDVo+kzve3dsIy9B+WHx+4R95rj23OnEP8DhAAevt1/m0SjmxKtEPURnZSP4Y9gH50hvrYl5hlNeZdERfS9PwmbjprH7miXMzx3wZQgV6+SuHU9vZxCejx22hcnNv8gxO6xbtQMhLX8OVe2wN"
    with_items:
    - pi
    - filippo
  - user: name=pi password="!"

  # manually installed minicom and tmux

  - lineinfile: dest=/etc/ssh/sshd_config regexp='^#?\s*{{ item }}' line="{{ item }} no"
    with_items:
      - PermitRootLogin
      - ChallengeResponseAuthentication
      - PasswordAuthentication
  - service: name=ssh state=reloaded

  - lineinfile: dest=/boot/config.txt line="dtoverlay=dwc2"
  - replace: dest=/boot/cmdline.txt regexp="rootwait$" replace="rootwait dtoverlay=dwc2"

  - lineinfile: dest=/etc/modules line=g_multi state=absent
  - file: dest=/etc/modprobe.d/multigadget.conf state=absent

  - lineinfile: dest=/etc/modules line=libcomposite
  - copy: src=usbgadget.sh dest=/usr/local/bin/usbgadget.sh mode=0755
  - copy: src=usbgadget.service dest=/etc/systemd/system/usbgadget.service
  # - get_url:
  #     url: http://dl-cdn.alpinelinux.org/alpine/v3.8/releases/x86_64/alpine-standard-3.8.0-x86_64.iso
  #     checksum: "sha256:9da0f7c2dd8ea55a542b19150012f3fa4e94724eb67cb3777b8027a872e3cc30"
  #     dest: /var/lib/alpine-standard-3.8.0-x86_64.iso
  - copy: src=alpine-standard-3.8.0-x86_64.iso dest=/var/lib/alpine-standard-3.8.0-x86_64.iso
  - systemd: daemon_reload=yes name=usbgadget.service state=started enabled=yes
